
class AuthResponseCodes:
    
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_NOT_AUTHORIZATION = "AUTH_NOT_AUTHORIZATION"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_USER_DISABLE = "AUTH_USER_DISABLE"