
class RolResponseCodes:
    
    ROL_CREATED = "ROL_CREATED",
    ROL_EXIST = "ROL_EXIST",
    ROL_PERMISSION_EMPTY = "ROL_PERMISSION_EMPTY",
    ROL_NOT_FOUND = "ROL_NOT_FOUND",
    ROL_PAGINATE_SUCCESS = "ROL_PAGINATE_SUCCESS",
    ROL_PAGINATE_ERROR = "ROL_PAGINATE_ERROR",
    ROL_DISABLE_SUCCESS = "ROL_DISABLE_SUCCESS",
    ROL_ENABLE_SUCCESS = "ROL_ENABLE_SUCCESS",