"""eliminar campo hola de rol

Revision ID: 6baa89e78d32
Revises: 772d29b7b1c7
Create Date: 2026-08-01 18:21:27.586511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6baa89e78d32'
down_revision: Union[str, Sequence[str], None] = '772d29b7b1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'rol_Hola')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('rol_Hola', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
