"""campo hola en rol

Revision ID: 772d29b7b1c7
Revises: f9ed6cf5b439
Create Date: 2026-08-01 18:20:33.592165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772d29b7b1c7'
down_revision: Union[str, Sequence[str], None] = 'f9ed6cf5b439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('rol_Hola', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'rol_Hola')
    # ### end Alembic commands ###
