"""principal

Revision ID: f9ed6cf5b439
Revises: 
Create Date: 2026-08-01 18:16:29.066939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ed6cf5b439'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('modulo_Id', sa.Integer(), nullable=False),
    sa.Column('modulo_Indice', sa.Integer(), nullable=False),
    sa.Column('modulo_Nombre', sa.String(length=100), nullable=False),
    sa.Column('modulo_Codigo', sa.String(length=100), nullable=False),
    sa.Column('modulo_Activo', sa.Boolean(), nullable=False),
    sa.Column('modulo_Creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modulo_Modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('modulo_Id')
    )
    op.create_table('opciones',
    sa.Column('opci_Id', sa.Integer(), nullable=False),
    sa.Column('opci_Nombre', sa.String(length=100), nullable=False),
    sa.Column('opci_Slug', sa.String(length=100), nullable=False),
    sa.Column('opci_Codigo', sa.String(length=100), nullable=False),
    sa.Column('opci_SubmoduloId', sa.Integer(), nullable=False),
    sa.Column('opci_Activo', sa.Boolean(), nullable=False),
    sa.Column('opci_Creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('opci_Modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('opci_Id')
    )
    op.create_table('rol_permisos',
    sa.Column('perol_Id', sa.Integer(), nullable=False),
    sa.Column('perol_RolId', sa.Integer(), nullable=False),
    sa.Column('perol_OpcionId', sa.Integer(), nullable=False),
    sa.Column('perol_Crear', sa.Boolean(), nullable=False),
    sa.Column('perol_Editar', sa.Boolean(), nullable=False),
    sa.Column('perol_CambiarEstado', sa.Boolean(), nullable=False),
    sa.Column('perol_CreacionId', sa.Integer(), nullable=False),
    sa.Column('perol_ModificacionId', sa.Integer(), nullable=False),
    sa.Column('perol_Creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('perol_Modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('perol_Id')
    )
    op.create_table('roles',
    sa.Column('rol_Id', sa.Integer(), nullable=False),
    sa.Column('rol_Nombre', sa.String(length=60), nullable=False),
    sa.Column('rol_Codigo', sa.String(length=60), nullable=False),
    sa.Column('rol_Descripcion', sa.String(length=200), nullable=False),
    sa.Column('rol_Activo', sa.Boolean(), nullable=False),
    sa.Column('rol_Creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rol_Modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rol_CreacionId', sa.Integer(), nullable=False),
    sa.Column('rol_ModificacionId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rol_Id'),
    sa.UniqueConstraint('rol_Nombre')
    )
    op.create_table('submodulos',
    sa.Column('submo_Id', sa.Integer(), nullable=False),
    sa.Column('submo_ModuloId', sa.Integer(), nullable=False),
    sa.Column('submo_Indice', sa.Integer(), nullable=False),
    sa.Column('submo_Nombre', sa.String(length=100), nullable=False),
    sa.Column('submo_Activo', sa.Boolean(), nullable=False),
    sa.Column('submo_Codigo', sa.String(length=100), nullable=False),
    sa.Column('submo_Creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('submo_Modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('submo_Id')
    )
    op.create_table('usuarios',
    sa.Column('usua_Id', sa.Integer(), nullable=False),
    sa.Column('usua_Nombre', sa.String(length=100), nullable=False),
    sa.Column('usua_RolId', sa.Integer(), nullable=False),
    sa.Column('usua_NombreUsuario', sa.String(length=100), nullable=False),
    sa.Column('usua_Contrasenia', sa.String(length=100), nullable=False),
    sa.Column('usua_Activo', sa.Boolean(), nullable=False),
    sa.Column('usua_Creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usua_Modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usua_CreacionId', sa.Integer(), nullable=False),
    sa.Column('usua_ModificacionId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('usua_Id')
    )
    op.create_table('usuarios_permisos',
    sa.Column('peusua_Id', sa.Integer(), nullable=False),
    sa.Column('peusua_UsuarioId', sa.Integer(), nullable=False),
    sa.Column('peusua_OpcionId', sa.Integer(), nullable=False),
    sa.Column('peusua_Crear', sa.Boolean(), nullable=False),
    sa.Column('peusua_Editar', sa.Boolean(), nullable=False),
    sa.Column('peusua_CambiarEstado', sa.Boolean(), nullable=False),
    sa.Column('peusua_Creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('peusua_Modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('peusua_CreacionId', sa.Integer(), nullable=False),
    sa.Column('peusua_ModificacionId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('peusua_Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_permisos')
    op.drop_table('usuarios')
    op.drop_table('submodulos')
    op.drop_table('roles')
    op.drop_table('rol_permisos')
    op.drop_table('opciones')
    op.drop_table('modulos')
    # ### end Alembic commands ###
