name: CD BMS

on:
  workflow_dispatch

jobs:

  cd:

    runs-on: ubuntu-latest
    
    steps:
      - name: Crear carpeta .ssh
        run: |
          mkdir ~/.ssh
      - name: Agregar llave
        run: echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519

      - name: Verificar llave
        run: |
          ls -la ~/.ssh
