name: CD BMS

on:
  workflow_dispatch

jobs:

  cd:

    runs-on: ubuntu-latest
    
    steps:
      - name: Crear carpeta .ssh
        run: |
          mkdir ~/.ssh
      - name: Agregar llave
        run: echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519

      - name: Verificar llave
        run: |
          ls -la ~/.ssh
      
      - name: Configurar permisos
        run: chmod 600 ~/.ssh/id_ed25519

      - name: Probar conexión al servidor
        run: |
          timeout 5 bash -c "</dev/tcp/192.168.1.65/22"
      - name: Agregar servidor a known_hosts
        run: ssh-keyscan ${{secrets.SERVER_HOST}} >> ~/.ssh/known_hosts

      - name: Prueba de conexion
        run: | 
          ${{secrets.MYSQL_USER}}@${{secrets.MYSQL_HOST}} "echo hola mundo"
