name: CD BMS

on:
  workflow_dispatch:

jobs:

  cd:

    runs-on: ubuntu-latest
    
    steps:
      - name: Conectar a Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
      
      - name: Crear carpeta SSH
        run: |
          mkdir -p ~/.ssh

      - name: Agregar llave privada
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

      - name: Configurar permisos
        run: |
          chmod 600 ~/.ssh/id_ed25519
      - name: Agregar servidor a known_hosts
        run: |
          ssh-keyscan ${{ secrets.TAILSCALE_IP }} >> ~/.ssh/known_hosts

      - name: Actualizar proyecto
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.TAILSCALE_IP }} "
            cd ~/projects/bms/BMS_BACKEND &&
            git pull origin main &&
            export ENV=prod &&
            .venv/bin/pip install -r requirements.txt &&
            .venv/bin/alembic upgrade head &&
            sudo systemctl restart bms-backend &&
            sudo systemctl is-active --quiet bms-backend
          "