name: Deploy

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    env: 
      ENV: test

    services:

      mysql:

        image: mysql:8.0

        env:
          MYSQL_USER: bms
          MYSQL_PASSWORD: bmstester
          MYSQL_ROOT_PASSWORD: bms
          MYSQL_DATABASE: bms_test
        
        ports:
          - 3306:3306
        
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3


    steps:

      - name: Clonar proyecto
        uses: actions/checkout@v5
      
      - name: Instalar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Agregar .env.test
        run: |
          cat > .env.test <<EOF 
          MYSQL_HOST=localhost
          MYSQL_PORT=3306
          APP_PORT=8000
          MYSQL_USER=bms
          MYSQL_PASSWORD=bmstester
          MYSQL_DB=bms_test
          EOF

      - name: Ejecutar alembic
        run: alembic upgrade head

      - name: Ejecutar pruebas
        run: pytest -v


