name: Mostrar poyecto

on:
  workflow_dispatch:
jobs:
  
  backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{secrets.APP_NAME}}
      - run: echo ${{secrets.APP_PORT}}
      - run: echo ${{secrets.APP_HOST}}
      

