name: Primer workflow

on:
  push:
    branches:
      - main

jobs:
  
  saludar:
    runs-on: ubuntu-latest
    
    steps:
      - name: saludar
        run: echo "Hola francisco"
  
  despedirse:
    runs-on: ubuntu-latest

    steps:
      - name: despedir
        run: echo "Adios"
