name: CD BMS

on:
  workflow_dispatch:

jobs:

  cd:

    runs-on: ubuntu-latest
    
    steps:
      - name: Conectar a Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
      
      - name: Verificar tailscale
        run: |
          tailscale status

      - name: Verificar conexion
        run: |
          tailscale ping ${{secrets.TAILSCALE_IP}}

